# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/imageProcessingSystem/imageProcessingSystem.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==imageProcessingSystem || ORIG_REF_NAME==imageProcessingSystem} -quiet] -quiet

# IP: bd/imageProcessingSystem/ip/imageProcessingSystem_processing_system7_0_0/imageProcessingSystem_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==imageProcessingSystem_processing_system7_0_0 || ORIG_REF_NAME==imageProcessingSystem_processing_system7_0_0} -quiet] -quiet

# IP: bd/imageProcessingSystem/ip/imageProcessingSystem_imageProcessTop_0_1/imageProcessingSystem_imageProcessTop_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==imageProcessingSystem_imageProcessTop_0_1 || ORIG_REF_NAME==imageProcessingSystem_imageProcessTop_0_1} -quiet] -quiet

# IP: bd/imageProcessingSystem/ip/imageProcessingSystem_axi_dma_0_1/imageProcessingSystem_axi_dma_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==imageProcessingSystem_axi_dma_0_1 || ORIG_REF_NAME==imageProcessingSystem_axi_dma_0_1} -quiet] -quiet

# IP: bd/imageProcessingSystem/ip/imageProcessingSystem_auto_pc_0/imageProcessingSystem_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==imageProcessingSystem_auto_pc_0 || ORIG_REF_NAME==imageProcessingSystem_auto_pc_0} -quiet] -quiet

# IP: bd/imageProcessingSystem/ip/imageProcessingSystem_ps7_0_axi_periph_1/imageProcessingSystem_ps7_0_axi_periph_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==imageProcessingSystem_ps7_0_axi_periph_1 || ORIG_REF_NAME==imageProcessingSystem_ps7_0_axi_periph_1} -quiet] -quiet

# IP: bd/imageProcessingSystem/ip/imageProcessingSystem_rst_ps7_0_100M_1/imageProcessingSystem_rst_ps7_0_100M_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==imageProcessingSystem_rst_ps7_0_100M_1 || ORIG_REF_NAME==imageProcessingSystem_rst_ps7_0_100M_1} -quiet] -quiet

# IP: bd/imageProcessingSystem/ip/imageProcessingSystem_xbar_0/imageProcessingSystem_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==imageProcessingSystem_xbar_0 || ORIG_REF_NAME==imageProcessingSystem_xbar_0} -quiet] -quiet

# IP: bd/imageProcessingSystem/ip/imageProcessingSystem_auto_us_0/imageProcessingSystem_auto_us_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==imageProcessingSystem_auto_us_0 || ORIG_REF_NAME==imageProcessingSystem_auto_us_0} -quiet] -quiet

# IP: bd/imageProcessingSystem/ip/imageProcessingSystem_auto_us_1/imageProcessingSystem_auto_us_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==imageProcessingSystem_auto_us_1 || ORIG_REF_NAME==imageProcessingSystem_auto_us_1} -quiet] -quiet

# IP: bd/imageProcessingSystem/ip/imageProcessingSystem_auto_pc_1/imageProcessingSystem_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==imageProcessingSystem_auto_pc_1 || ORIG_REF_NAME==imageProcessingSystem_auto_pc_1} -quiet] -quiet

# IP: bd/imageProcessingSystem/ip/imageProcessingSystem_axi_mem_intercon_0/imageProcessingSystem_axi_mem_intercon_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==imageProcessingSystem_axi_mem_intercon_0 || ORIG_REF_NAME==imageProcessingSystem_axi_mem_intercon_0} -quiet] -quiet

# IP: bd/imageProcessingSystem/ip/imageProcessingSystem_xlconcat_0_0/imageProcessingSystem_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==imageProcessingSystem_xlconcat_0_0 || ORIG_REF_NAME==imageProcessingSystem_xlconcat_0_0} -quiet] -quiet

# IP: bd/imageProcessingSystem/ip/imageProcessingSystem_system_ila_0_0/imageProcessingSystem_system_ila_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==imageProcessingSystem_system_ila_0_0 || ORIG_REF_NAME==imageProcessingSystem_system_ila_0_0} -quiet] -quiet

# XDC: bd/imageProcessingSystem/imageProcessingSystem_ooc.xdc
