# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/danya/Downloads/imageProcessingSystem/imageProcessingSystem.srcs/sources_1/bd/imageProcessingSystem/ip/imageProcessingSystem_imageProcessTop_0_1/imageProcessingSystem_imageProcessTop_0_1.xci
# IP: The module: 'imageProcessingSystem_imageProcessTop_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/danya/Downloads/imageProcessingSystem/imageProcessingSystem.srcs/sources_1/bd/imageProcessingSystem/ip/imageProcessingSystem_imageProcessTop_0_1/newtutorial.srcs/sources_1/ip/outputBuffer/outputBuffer.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==outputBuffer || ORIG_REF_NAME==outputBuffer} -quiet] -quiet

# XDC: c:/Users/danya/Downloads/imageProcessingSystem/imageProcessingSystem.srcs/sources_1/bd/imageProcessingSystem/ip/imageProcessingSystem_imageProcessTop_0_1/newtutorial.srcs/sources_1/ip/outputBuffer/outputBuffer.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==outputBuffer || ORIG_REF_NAME==outputBuffer} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# IP: c:/Users/danya/Downloads/imageProcessingSystem/imageProcessingSystem.srcs/sources_1/bd/imageProcessingSystem/ip/imageProcessingSystem_imageProcessTop_0_1/imageProcessingSystem_imageProcessTop_0_1.xci
# IP: The module: 'imageProcessingSystem_imageProcessTop_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/danya/Downloads/imageProcessingSystem/imageProcessingSystem.srcs/sources_1/bd/imageProcessingSystem/ip/imageProcessingSystem_imageProcessTop_0_1/newtutorial.srcs/sources_1/ip/outputBuffer/outputBuffer.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==outputBuffer || ORIG_REF_NAME==outputBuffer} -quiet] -quiet

# XDC: c:/Users/danya/Downloads/imageProcessingSystem/imageProcessingSystem.srcs/sources_1/bd/imageProcessingSystem/ip/imageProcessingSystem_imageProcessTop_0_1/newtutorial.srcs/sources_1/ip/outputBuffer/outputBuffer.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==outputBuffer || ORIG_REF_NAME==outputBuffer} -quiet] {/U0 } ]/U0 ] -quiet] -quiet
