# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/danya/Downloads/imageProcessingSystem/imageProcessingSystem.srcs/sources_1/bd/imageProcessingSystem/ip/imageProcessingSystem_axi_dma_0_1/imageProcessingSystem_axi_dma_0_1.xci
# IP: The module: 'imageProcessingSystem_axi_dma_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/danya/Downloads/imageProcessingSystem/imageProcessingSystem.srcs/sources_1/bd/imageProcessingSystem/ip/imageProcessingSystem_axi_dma_0_1/imageProcessingSystem_axi_dma_0_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'imageProcessingSystem_axi_dma_0_1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/danya/Downloads/imageProcessingSystem/imageProcessingSystem.srcs/sources_1/bd/imageProcessingSystem/ip/imageProcessingSystem_axi_dma_0_1/imageProcessingSystem_axi_dma_0_1_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'imageProcessingSystem_axi_dma_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/danya/Downloads/imageProcessingSystem/imageProcessingSystem.srcs/sources_1/bd/imageProcessingSystem/ip/imageProcessingSystem_axi_dma_0_1/imageProcessingSystem_axi_dma_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'imageProcessingSystem_axi_dma_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Users/danya/Downloads/imageProcessingSystem/imageProcessingSystem.srcs/sources_1/bd/imageProcessingSystem/ip/imageProcessingSystem_axi_dma_0_1/imageProcessingSystem_axi_dma_0_1.xci
# IP: The module: 'imageProcessingSystem_axi_dma_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/danya/Downloads/imageProcessingSystem/imageProcessingSystem.srcs/sources_1/bd/imageProcessingSystem/ip/imageProcessingSystem_axi_dma_0_1/imageProcessingSystem_axi_dma_0_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'imageProcessingSystem_axi_dma_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/danya/Downloads/imageProcessingSystem/imageProcessingSystem.srcs/sources_1/bd/imageProcessingSystem/ip/imageProcessingSystem_axi_dma_0_1/imageProcessingSystem_axi_dma_0_1_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'imageProcessingSystem_axi_dma_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/danya/Downloads/imageProcessingSystem/imageProcessingSystem.srcs/sources_1/bd/imageProcessingSystem/ip/imageProcessingSystem_axi_dma_0_1/imageProcessingSystem_axi_dma_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'imageProcessingSystem_axi_dma_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
